version: 2.1
defaults: &defaults
  docker:
    - image: vampio/kmt:circleci-latest
jobs:
  generate-k8s-artifacts:
    <<: *defaults
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "68:e9:39:38:a9:73:a7:bd:05:dc:20:4e:a5:e2:9a:1c"
      - run:
          name: Calculate
          command: |
            cd tutorial5
            for filename in applications/*/*.{json,yaml,yml}; do
              [ -e "$filename" ] || continue
              ext="${filename##*.}"
              base=$(basename "$filename" ."$ext")
              echo "$filename", "$basename"
              vamp-kmt -A "$filename" -s services/ -e environments/ -o .
            done
            ls -la

workflows:
  version: 2
  publish-version:
    jobs:
      - generate-k8s-artifacts
