version: 2.1
defaults: &defaults
  docker:
    - image: vampio/kmt:circleci-latest
jobs:
  generate-k8s-artifacts:
    <<: *defaults
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "68:e9:39:38:a9:73:a7:bd:05:dc:20:4e:a5:e2:9a:1c"
      - run:
          name: Calculate
          command: |
            cd tutorial5
            for filepath in applications/*/*.{json,yaml,yml}; do
              [ -e "$filepath" ] || continue
              path=$(dirname "$filepath")
              dirname=$(basename "$path")
              ext="${filepath##*.}"
              filename=$(basename "$filepath" ."$ext")
              echo "$filepath", "$dirname", "$filename"
              vamp-kmt -A "$filepath" -s services/ -e environments/ -D ../k8s-templates/deployment-template.jsonnet -o $subdir
            done
            ls -la
            ls -la $subdir

workflows:
  version: 2
  publish-version:
    jobs:
      - generate-k8s-artifacts
